# Generated by Django 4.0.6 on 2022-07-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domasna5', '0002_rename_quiz_quize_rename_results_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quize',
            new_name='Quiz',
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
