# Generated by Django 4.0.4 on 2022-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domasna5', '0006_delete_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
            ],
        ),
    ]
