# Generated by Django 4.0.4 on 2022-07-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domasna5', '0007_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
