# Generated by Django 4.0.4 on 2022-07-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domasna5', '0013_quizprofile_attemptedquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='isCorrectAnswer',
            new_name='correctAnswer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modified',
        ),
        migrations.DeleteModel(
            name='AttemptedQuestion',
        ),
        migrations.DeleteModel(
            name='QuizProfile',
        ),
    ]
